## 服务器端口号
server:
  application:
    name: schedule-server
  port: ${SERVER_PORT:8011}
  tomcat:
    uri-encoding: UTF-8

schedule:
  server:
    transport:
      config:
        connectionTimeOut: 5000
    register:
      config:
        namespace: 431b3916-40d9-4710-aa25-dce3c438cf2b
        serverList:
          - 10.107.119.133:8842
    task:
      notifyType: KAFKA

## 关于数据库参数的相关配置
task:
  schedule:
    ## 调度任务线程数
    generateTask: 10
    ##分发任务线程数
    dispatchTask: 20
    ## 获取待任务分发列表时，向前预取多少秒内待下发的任务
    dispatchTimeRange: 5
    ## 获取待调度任务时，向前预取多少秒内待触发的任务
    generateTimeRange: 30
